### ISSUE TITLE
Question: are cgi calls all queued?

### ISSUE THREAD

**Issue by IcedQuinn** [reddec/trusted-cgi#1]
I saw one example uses an Sqlite database but only one process at a time can write to them. Does `trusted-cgi` only run a single function at a time on the server?

**Comment by reddec** [comment]
Within one instance lambdas will be invoked strictly one by one. 
This could be changed in the future, please, do not rely on it unless if it will not be mentioned explicitly in the documentation.
I specifically wrote an example with SQLite, because SQLite can handle multi-processing lock internally (basically - using internal lock files).
Please, feel free to enrich documentation by PR if you will find more edge-cases.
